name: Publish to NPM

on:
  # Not needed since the referenced workflow pushes a new version tag which triggers this workflow
  # workflow_run:
  #   workflows: ['Bump Version on Close Pull Request']
  #   types:
  #     - completed

  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm install && npm run build:production
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
