name: Bump Version on Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  merge_job:
    # this job will only run if the PR has been merged and is 'main' branch
    # if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Test Build
        run: yarn install && yarn run build:production
      - name: Bump Version
        run: |
          git config --global user.name "florianporada"
          git config --global user.email "florianporada@users.noreply.github.com"

          echo "Remove build related folders"
          rm -rf node_modules
          rm -rf dist

          echo PR #${{ github.event.number }} has been merged
          echo "Bumping version (patch)"
          yarn version --patch
          git push
